# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - github-pages
  - bourbon
  - webrick

# Site settings
title: "Melissa Harper"
description: > # this means to ignore newlines until "email:"
   .

#email: a-mail@mail.mail
#blog logo
logo: "/assets/images/h_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/gateway_arch.jpg"

name: "Melissa Harper"
author: "Melissa Harper"
author_image: "/assets/images/harper.jpg"

paginate:	5

url: "https://melissaharper.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: "@dirkfabisch"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#   - icon:	twitter
#     url:
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

# #  - icon:
# #    url:
# #    desc: Connect with me facebook
# #    share_url: https://www.facebook.com/sharer.php
# #    share_title: ?t=
# #    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/melissaharper
    desc:	
    share_url:
    share_title:
    share_link:

 #- icon:	linkedin
  #  url:	www.linkedin.com/in/harper-melissa
# #    desc:
# #    share_url:
# #    share_title:
# #    share_link:
